### ISSUE TITLE
file to import not found or unreadable

### ISSUE THREAD

**Issue by freder** [dlmanning/gulp-sass#134]
i just revisited a project, and updated all the dependencies, including gulp-sass.
sass would previously compile without any problems, but with the latest version of gulp-sass (1.2.3) i get errors. so i worked my way back to a version that actually works, which turns out to be 1.1.0.

the errors i'm getting for 1.2.0-1.2.2 are #124.

```shell
# ——————————
% npm install && npm ls --depth=0 | grep "gulp-sass" && npm ls --depth=0 | grep "node-bourbon" && gulp sass
# [...]
├── gulp-sass@1.1.0
├── node-bourbon@1.2.3
[11:50:45] Using gulpfile /project-path/code/thing/gulpfile.js
[11:50:45] Starting 'sass'...
[11:50:45] Finished 'sass' after 123 ms


# ——————————
% npm install && npm ls --depth=0 | grep "gulp-sass" && npm ls --depth=0 | grep "node-bourbon" && gulp sass
# [...]
├── gulp-sass@1.2.0
├── node-bourbon@1.2.3
[11:51:58] Using gulpfile /project-path/code/thing/gulpfile.js
[11:51:58] Starting 'sass'...

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
TypeError: Cannot call method 'pop' of undefined
    at nodeSass (/project-path/code/thing/node_modules/gulp-sass/index.js:84:46)
    at wrappedMapper (/project-path/code/thing/node_modules/gulp-sass/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/project-path/code/thing/node_modules/gulp-sass/node_modules/map-stream/index.js:96:21)
    at write (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)


# ——————————
% npm install && npm ls --depth=0 | grep "gulp-sass" && npm ls --depth=0 | grep "node-bourbon" && gulp sass
# [...]
├── gulp-sass@1.2.1
├── node-bourbon@1.2.3
[11:52:38] Using gulpfile /project-path/code/thing/gulpfile.js
[11:52:38] Starting 'sass'...

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
TypeError: Cannot call method 'pop' of undefined
    at nodeSass (/project-path/code/thing/node_modules/gulp-sass/index.js:87:46)
    at wrappedMapper (/project-path/code/thing/node_modules/gulp-sass/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/project-path/code/thing/node_modules/gulp-sass/node_modules/map-stream/index.js:96:21)
    at write (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)


# ——————————
% npm install && npm ls --depth=0 | grep "gulp-sass" && npm ls --depth=0 | grep "node-bourbon" && gulp sass
# [...]
├── gulp-sass@1.2.2
├── node-bourbon@1.2.3
[11:52:59] Using gulpfile /project-path/code/thing/gulpfile.js
[11:52:59] Starting 'sass'...

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
TypeError: Cannot call method 'pop' of undefined
    at nodeSass (/project-path/code/thing/node_modules/gulp-sass/index.js:95:46)
    at wrappedMapper (/project-path/code/thing/node_modules/gulp-sass/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/project-path/code/thing/node_modules/gulp-sass/node_modules/map-stream/index.js:96:21)
    at write (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/project-path/code/thing/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)


# ——————————
% npm install && npm ls --depth=0 | grep "gulp-sass" && npm ls --depth=0 | grep "node-bourbon" && gulp sass
# [...]
├── gulp-sass@1.2.3
├── node-bourbon@1.2.3
[11:53:20] Using gulpfile /project-path/code/thing/gulpfile.js
[11:53:20] Starting 'sass'...
[11:53:20] [gulp-sass] stdin:2: file to import not found or unreadable: "bourbon"
Current dir:

[11:53:20] [gulp-sass] /project-path/code/thing/resources/sass/common:2: file to import not found or unreadable: "bourbon"
Current dir: /project-path/code/thing/resources/sass/

[11:53:20] Finished 'sass' after 175 ms
```

```javascript
var sass = require('gulp-sass');
var bourbon = require('node-bourbon');
var path = require('path');

var paths = {
	include: [
		'bower_components/scut/dist/',
		'bower_components/normalize-scss/',
		'bower_components/compass-mixins/lib/',
		'bower_components/bootstrap-sass-official/assets/stylesheets/',
		'resources/sass/'
	].concat(bourbon.includePaths),
	src: 'resources/sass/*.scss',
	example_src: './*/resources/sass/*.scss'
};

var sass_params = {
	includePaths: paths.include,
	// sourceComments: 'map',
	// sourceMap: 'sass',
	errLogToConsole: true
};

gulp.task('sass', function() {
	return gulp.src(paths.src)
		.pipe( sass(sass_params) )
		.pipe( gulp.dest('resources/css') );
});

gulp.task('watch_sass', function() {
	// main sass files
	gulp.watch(paths.src, ['sass']);

	// example-specific sass files
	gulp.watch(paths.example_src, function(event) {
		var base = path.dirname(event.path);
		return gulp.src(paths.example_src, { base: base })
			.pipe( sass(sass_params) )
			.pipe( gulp.dest( path.join(base, '../css/') ) );
	});
});
```

`_bourbon.scss` (from [node-bourbon](https://github.com/lacroixdesign/node-bourbon)) does exist, but for some reason it can't be found. — any ideas why that could be?

thanks a lot in advance.

**Comment by Keats** [comment]
Issues probably already fixed judging by the date, if it still happens in the latest npm version try the 2.x branch.
If it still happens then reopen it and I'll add a failing test case

**Comment by saltict** [comment]
Sass error: { status: 1,
  file: 'E:/WORKSPACE/Aqua/src/scss/main.scss',
  line: 32,
  column: 9,
  message: 'file to import not found or unreadable: component/bu
tton\nCurrent dir: E:/WORKSPACE/Aqua/src/scss/',
  code: 1 }
[BS] 1 file changed (plugins.css)

This issue occur when is save file in sub folder with exactly the file i save.

**Comment by Keats** [comment]
@saltict are you using 2.x branch ?

**Comment by TheDutchCoder** [comment]
Having this issue al of a sudden with 1.3.3 on Windows 7.

**Comment by andy-hook** [comment]
I am also experiencing this issue, 1.3.3 on Windows 8

**Comment by ImBobby** [comment]
had a similar issue on Windows 8 using 1.3.3. It happen once out of 10. Upgraded to 2.0.3 today and all imported files are not readable.
