### ISSUE TITLE
Can't run on io.js 1.0.1

### ISSUE THREAD

**Issue by kasperekt** [dlmanning/gulp-sass#172]
Plugin worked fine on node v0.10.35 but when I switched to io.js 1.0.1, gulp returns error:

````
module.js:341
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/tomek/Dev/Kama/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:211:15)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
````

**Comment by dlmanning** [comment]
@kasperekt : I believe this is a problem with node-sass. Be patient, io.js is till alpha software.
