### ISSUE TITLE
gulp-sass + merge2 = Error: Only readable stream can be merged.

### ISSUE THREAD

**Issue by parsnick** [dlmanning/gulp-sass#237]
I'm getting this error when trying to use gulp-sass and [merge2](https://github.com/teambition/merge2) to combine my CSS and SCSS files:

gulpfile.js
```javascript
var gulp = require('gulp');
var sass = require('gulp-sass');
var concat = require('gulp-concat');
var merge2 = require('merge2');

gulp.task('default', function () {

	return merge2(
		gulp.src('already-compiled.css'),
		gulp.src('needs-compiling.scss').pipe(sass())
	)
		.pipe(concat('bundle.css'))
		.pipe(gulp.dest('.'));

});
```

If I remove the `.pipe(sass())`, the task completes as expected.

Stacktrace:
```sh
[02:41:42] Using gulpfile /var/www/gulp-sass-merge2/gulpfile.js
[02:41:42] Starting 'default'...
[02:41:42] 'default' errored after 4.51 ms
[02:41:42] Error: Only readable stream can be merged.
    at pauseStreams (/var/www/gulp-sass-merge2/node_modules/merge2/index.js:92:13)
    at addStream (/var/www/gulp-sass-merge2/node_modules/merge2/index.js:29:25)
    at merge2 (/var/www/gulp-sass-merge2/node_modules/merge2/index.js:84:30)
    at Gulp.<anonymous> (/var/www/gulp-sass-merge2/gulpfile.js:9:9)
    at module.exports (/var/www/gulp-sass-merge2/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/gulp-sass-merge2/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/gulp-sass-merge2/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/var/www/gulp-sass-merge2/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:448:13)
```

Cloneable example: https://github.com/parsnick/gulp-sass-merge2-error

**Comment by parsnick** [comment]
I've just noticed this only occurs with merge2 >= 0.3.2. Earlier versions work fine so I don't know if the issue is with this plugin or merge2.

**Comment by zensh** [comment]
this problem is cause  by https://github.com/dominictarr/map-stream, `map-stream` is out of date.

merge2 should work with readable streams.

**Comment by parsnick** [comment]
Fair enough if this issue doesn't belong here but could you perhaps point me (and others who might come across this) in the right direction? Does an issue need raising for `map-stream`? Does `gulp-sass` only work with an earlier version of node? Is there a solution / workaround for this simple use case?

**Comment by zensh** [comment]
@parsnick  You can try this:

```js
var gulp = require('gulp');
var sass = require('gulp-sass');
var concat = require('gulp-concat');
var PassThrough = require('stream').PassThrough;
var merge2 = require('merge2');

gulp.task('default', function () {

    return merge2(
        gulp.src('already-compiled.css'),
        gulp.src('needs-compiling.scss').pipe(sass()).pipe(PassThrough({objectMode: true}))
    )
        .pipe(concat('bundle.css'))
        .pipe(gulp.dest('.'));

});
```

I think that `gulp-sass` should refactor code with `through2`

**Comment by Snugug** [comment]
Our [2.x branch](https://github.com/dlmanning/gulp-sass/blob/2.x/index.js) uses `through2`

I closed as you had a response from the maintainer of `merge` in both places

**Comment by zensh** [comment]
:+1:

**Comment by parsnick** [comment]
@zensh Brilliant, thank you, that works perfectly.

@Snugug Yes, that would have been fine *if* the problem was actually with `merge2`, as opposed to one of `gulp-sass`'s dependencies :stuck_out_tongue: Never mind, resolved now, thank you.

**Comment by Snugug** [comment]
@parsnick I see what's going on now. Either way, it's been resolved.
