### ISSUE TITLE
[2.x] gulp-sourcemaps: 'No element indexed by ' + aIdx 

### ISSUE THREAD

**Issue by parsnick** [dlmanning/gulp-sass#241]
Not sure if you're interested in issues from the 2.x branch yet so close if not relevant, but just ran into this problem using the 2.0 alpha with `gulp-sourcemaps`.

Trying to compile the bootstrap-sass package from bower and generating sourcemaps produces this error:
```js
/media/nick/Dev/sites/gulp-sass-sourcemaps/node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/array-set.js:83
    throw new Error('No element indexed by ' + aIdx);
          ^
Error: No element indexed by -1
    at ArraySet_at [as at] (/media/nick/Dev/sites/gulp-sass-sourcemaps/node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/array-set.js:83:11)
    at SourceMapConsumer_parseMappings [as _parseMappings] (/media/nick/Dev/sites/gulp-sass-sourcemaps/node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:229:44)
    at SourceMapConsumer.Object.defineProperty.get (/media/nick/Dev/sites/gulp-sass-sourcemaps/node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:164:14)
    at SourceMapConsumer_eachMapping [as eachMapping] (/media/nick/Dev/sites/gulp-sass-sourcemaps/node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:547:24)
    at Function.SourceMapGenerator_fromSourceMap (/media/nick/Dev/sites/gulp-sass-sourcemaps/node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-generator.js:52:26)
    at applySourceMap (/media/nick/Dev/sites/gulp-sass-sourcemaps/node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply/index.js:22:40)
    at filePush (/media/nick/Dev/sites/gulp-sass-sourcemaps/node_modules/gulp-sass/index.js:80:9)
    at Object.callback (/media/nick/Dev/sites/gulp-sass-sourcemaps/node_modules/gulp-sass/index.js:117:9)
    at options.success (/media/nick/Dev/sites/gulp-sass-sourcemaps/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:278:32)
```

**gulpfile.js**
```js
var gulp = require('gulp');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('default', function () {

	return gulp.src('my_bundle.scss')
		.pipe(sourcemaps.init())
		.pipe(sass())
		.pipe(sourcemaps.write())
		.pipe(gulp.dest('dist/'));

});
```

**my_bundle.scss**
```sass
$brand-primary: #CCC000;

@import "bower_components/bootstrap-sass/assets/stylesheets/bootstrap";
```

Repo to reproduce the error is at [parsnick/gulp-sass-sourcemaps-error](https://github.com/parsnick/gulp-sass-sourcemaps-error). Just run `install.sh` to grab the relevant packages from npm and bower, then try a `gulp` to see the error.

Easily fixed by downgrading `gulp-sass` to a stable version, just thought I'd throw in an issue in case you weren't aware.

**Comment by Snugug** [comment]
This is a know issue in libsass. I've reported it to them, but don't have a link handy. They haven't released a fix yet
