### ISSUE TITLE
TypeError: listener must be a function

### ISSUE THREAD

**Issue by iwilliams** [dlmanning/gulp-sass#315]
Recently my gulp task to build styles has started to fail with a very cryptic error message and I can't seem to find any fix. This ran fine before, I can't really say what has changed since then. I do however always seem to have to reinstall gulp-sass to get it to stop complaining about lib-sass bindings. My task looks like this:
```JS
gulp.task('sass', function() {
  gulp.src('./assets/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('./dev'));
});
```

And the error I'm getting:
```
[14:52:06] TypeError: listener must be a function
    at TypeError (native)
    at Stream.addListener (events.js:142:11)
    at Gulp.<anonymous> (/Applications/MAMP/htdocs/<REDACTED>/<REDACTED>/gulpfile.js:38:18)
    at module.exports (/Applications/MAMP/htdocs/<REDACTED>/<REDACTED>/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Applications/MAMP/htdocs/<REDACTED>/<REDACTED>/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Applications/MAMP/htdocs/<REDACTED>/<REDACTED>/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Applications/MAMP/htdocs/<REDACTED>/<REDACTED>/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/ianaw/.nvm/versions/node/v0.12.7/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
```

**Comment by LeoLeBras** [comment]
@iwilliams I have same problem, are you solve it?

**Comment by joelmatiassilva** [comment]
any help?

**Comment by LeoLeBras** [comment]
I don't know why sass.logError doesn't work ... so I write this : https://gist.github.com/LeoLeBras/0c362eaa447ebc7d7225.

**Comment by Keats** [comment]
Can one of you publish a repo with the issue?

**Comment by joelmatiassilva** [comment]
@Keats, 
is published the issue on this repo: https://github.com/joelmatiassilva/gulpSassProblem.git

**Comment by Keats** [comment]
your project uses gulp-sass 1.3.3, not gulp-sass 2
Install the latest version of gulp-sass and it should work

**Comment by joelmatiassilva** [comment]
Thanks @Keats!!!
:)

**Comment by LeoLeBras** [comment]
Thanks @Keats !

**Comment by hasekrx** [comment]
I have the same error and its not working but i do have the VERSION 2.1.1
can you help me @Keats ? S2

**Comment by Keats** [comment]
Are you sure you have v2.1.1 and not a v1 somewhere in your node_modules? 
`rm -rf node_modules && npm install`

**Comment by gaomeng1900** [comment]
Just remove ".on('error', sass.logError)" and it will be fine.

**Comment by DutchKev** [comment]
@gaomeng1900 and how would you log the errors then?

**Comment by veremey** [comment]
somebody help?

gulp.task('sass', function() {
    return gulp
        .src(config.src.sass + '**/*.sass')
        .pipe(sourcemaps.init())
        .pipe(sass().on('error', sass.logError))
        .pipe(postcss(processors))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest(config.dest.css));
});

**Comment by rojaz813** [comment]
### Thanks @LeoLeBras 
This actually solved _all my errors_.

> I don't know why sass.logError doesn't work ... so I write this in my gulp task: https://gist.github.com/LeoLeBras/0c362eaa447ebc7d7225.
