### ISSUE TITLE
is not a valid Win32 application

### ISSUE THREAD

**Issue by jesshaw** [dlmanning/gulp-sass#321]
// build styles to tmp
gulp.task('styles', ['clean'], function () {
  // compile css starting from each module's module.scss
  return gulp.src('app/*/styles/module.scss')
    .pipe($.plumber())
    .pipe($.sourcemaps.init())
    .pipe($.sass.sync().on('error', $.sass.logError))
    .pipe($.autoprefixer({ browsers: ['last 2 versions'], remove: false}))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('.tmp/'));
});

$ gulp styles
[09:22:13] Using gulpfile D:\Users\jes\Desktop\sb\mCordovaTest\gulpfile.js
[09:22:13] Starting 'clean'...
[09:22:13] Finished 'clean' after 14 ms
[09:22:13] Starting 'styles'...
[09:22:13] 'styles' errored after 260 ms
[09:22:13] Error: %1 is not a valid Win32 application.
D:\Users\jes\Desktop\sb\mCordovaTest\node_modules\gulp-sass\node_modules\node
-sass\vendor\win32-x64-14\binding.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\Users\mzxiao\Desktop\sb\mCordovaTest\node_modules\
gulp-sass\node_modules\node-sass\lib\index.js:16:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by NGalarneau** [comment]
Are you using Visual Studio 2015?

**Comment by Keats** [comment]
That is a node-sass issue, please open an issue on that repo
