### ISSUE TITLE
Unhandled 'error' event when including from a missing directory

### ISSUE THREAD

**Issue by deckar01** [dlmanning/gulp-sass#335]
**Environment**
OS X 10.10
gulp 3.9.0
gulp-sass 2.0.4

**Cause**
Compiling an `@include` statement that references a directory that does not exist.

**Example**
 `@import 'missing_directory/colors.scss';`

**Behavour**
`gulp-sass` crashes `gulp` with the following trace:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch ENOENT
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at Gaze._watchDir (/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
    at /node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
```

**Expected behavior**
The error is bubbled up as an "error" event that can be handled by the calling scope.

**Comment by deckar01** [comment]
The issue seems to be a problem with the `gaze` dependency used by `gulp` and not `gulp-sass` itself.

Duplicate of https://github.com/shama/gaze/issues/114.
