### ISSUE TITLE
Installation failed on Node 4.0.0

### ISSUE THREAD

**Issue by pmq20** [dlmanning/gulp-sass#342]
```
pmq20•~» tnpm i -g gulp-sass                                                         [14:30:54]
\
> node-sass@3.3.2 install /usr/local/lib/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.2/darwin-x64-46_binding.node": connect ETIMEDOUT 54.231.17.104:443

> node-sass@3.3.2 postinstall /usr/local/lib/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /usr/local/lib/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp.js rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp: /Users/pmq20/.node-gyp/4.0.0/common.gypi not found (cwd: /usr/local/lib/node_modules/gulp-sass/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp.js" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v4.0.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok 
Build failed
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/tnpm/node_modules/.bin/ali-npm" "--no-proxy" "--disturl=http://npm.taobao.org/mirrors/node" "--userconfig=/Users/pmq20/.tnpmrc" "--registry=http://registry.npm.alibaba-inc.com" "--node-gyp=/usr/local/lib/node_modules/tnpm/node_modules/node-gyp/bin/node-gyp.js" "--cache=/Users/pmq20/.tnpm" "i" "-g" "gulp-sass"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.3.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.3.2 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pmq20/npm-debug.log
pmq20•~»                                                                             [14:32:36]

```

**Comment by pmq20** [comment]
sorry, network issue
