### ISSUE TITLE
Old node-sass dependency fails to install

### ISSUE THREAD

**Issue by Zorgatone** [dlmanning/gulp-sass#363]
gulp-sass is using an out-of-date version of node-sass.
If I install node-sass it works... However I cannot install gulp-sass.

gulp-sass tries to install as a submodule node-sass v2.1.1 instead of v3.3.3 (which won't install on node 4.3 and/or linux).
I am using Nodejs v4.3 (not io.js) and Ubuntu 15.04 x64

Here is the install log:
```bash
bad5e7f1e@d3adb33f:vigi2$ npm install gulp-sass
npm WARN package.json vigi2@1.0.0 No repository field.
npm WARN package.json vigi2@1.0.0 No README data
npm WARN package.json vigi2@1.0.0 No license field.
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
-
> node-sass@2.1.1 install /home/bad5e7f1e/repos/vigi2/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/linux-x64-node-4.1/binding.node

> node-sass@2.1.1 postinstall /home/bad5e7f1e/repos/vigi2/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

make: Entering directory '/home/bad5e7f1e/repos/vigi2/node_modules/gulp-sass/node_modules/node-sass/build'
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cpp:1:0:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/binding.cpp:1:
/home/bad5e7f1e/.node-gyp/4.1.2/src/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/bad5e7f1e/.node-gyp/4.1.2/src/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/bad5e7f1e/.node-gyp/4.1.2/src/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/bad5e7f1e/.node-gyp/4.1.2/src/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/binding.cpp:1:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../src/binding.cpp: In function ‘void dispatched_async_uv_callback(uv_async_t*)’:
../src/binding.cpp:70:35: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/bad5e7f1e/.node-gyp/4.1.2/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(try_catch);
                                   ^
../src/binding.cpp: In function ‘void make_callback(uv_work_t*)’:
../src/binding.cpp:245:35: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/bad5e7f1e/.node-gyp/4.1.2/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(try_catch);
                                   ^
../src/binding.cpp: In function ‘void ImportedCallback(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/binding.cpp:365:35: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/bad5e7f1e/.node-gyp/4.1.2/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(try_catch);
                                   ^
binding.target.mk:128: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/bad5e7f1e/repos/vigi2/node_modules/gulp-sass/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/bad5e7f1e/repos/vigi2/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/lib/build.js:272:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-30-generic
gyp ERR! command "/usr/local/bin/node" "/home/bad5e7f1e/repos/vigi2/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/bad5e7f1e/repos/vigi2/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v4.1.2
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok 
Build failed
gulp-sass@1.3.3 node_modules/gulp-sass
├── clone@0.1.19
├── map-stream@0.1.0
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, object-assign@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, replace-ext@0.0.1, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, multipipe@0.1.2, through2@2.0.0, dateformat@1.0.11)
└── node-sass@2.1.1 (get-stdin@4.0.1, object-assign@2.1.1, replace-ext@0.0.1, semver@4.3.6, chalk@0.5.1, cross-spawn@0.2.9, mkdirp@0.5.1, nan@1.9.0, npmconf@2.1.2, gaze@0.5.2, mocha@2.3.3, sass-graph@1.3.0, meow@3.4.2, pangyp@2.3.2, request@2.64.0)
bad5e7f1e@d3adb33f:vigi2$ 
```

I've already read about people reporting this issue to node-sass, and they answered to update it to 3.3.3.
here is the node-sass install log (which works fine)...

```bash
bad5e7f1e@d3adb33f:vigi2$ npm install node-sass
npm WARN package.json vigi2@1.0.0 No repository field.
npm WARN package.json vigi2@1.0.0 No README data
npm WARN package.json vigi2@1.0.0 No license field.
 
> spawn-sync@1.0.13 postinstall /home/bad5e7f1e/repos/vigi2/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

/
> node-sass@3.3.3 install /home/bad5e7f1e/repos/vigi2/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/bad5e7f1e/repos/vigi2/node_modules/node-sass/vendor/linux-x64-46/binding.node

> node-sass@3.3.3 postinstall /home/bad5e7f1e/repos/vigi2/node_modules/node-sass
> node scripts/build.js

` /home/bad5e7f1e/repos/vigi2/node_modules/node-sass/vendor/linux-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
node-sass@3.3.3 node_modules/node-sass
├── get-stdin@4.0.1
├── async-foreach@0.1.3
├── nan@2.1.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── npmconf@2.1.2 (ini@1.3.4, uid-number@0.0.5, inherits@2.0.1, semver@4.3.6, nopt@3.0.4, config-chain@1.1.9, once@1.3.2, osenv@0.1.3)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@3.0.0)
├── cross-spawn@2.0.0 (cross-spawn-async@2.0.0, spawn-sync@1.0.13)
├── gaze@0.5.2 (globule@0.1.0)
├── meow@3.4.2 (trim-newlines@1.0.0, loud-rejection@1.0.0, object-assign@4.0.1, minimist@1.2.0, camelcase-keys@1.0.0, redent@1.0.0, normalize-package-data@2.3.4, read-pkg-up@1.0.1)
├── node-gyp@3.0.3 (graceful-fs@4.1.2, semver@5.0.3, osenv@0.1.3, nopt@3.0.4, minimatch@1.0.0, which@1.2.0, fstream@1.0.8, glob@4.5.3, tar@1.0.3, rimraf@2.4.3, path-array@1.0.0, npmlog@1.2.1)
├── request@2.64.0 (aws-sign2@0.5.0, forever-agent@0.6.1, tunnel-agent@0.4.1, oauth-sign@0.8.0, caseless@0.11.0, stringstream@0.0.4, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.0, node-uuid@1.4.3, qs@5.1.0, form-data@1.0.0-rc3, combined-stream@1.0.5, mime-types@2.1.7, http-signature@0.11.0, bl@1.0.0, hawk@3.1.0, har-validator@1.8.0)
└── sass-graph@2.0.1 (lodash@3.10.1, yargs@3.27.0)
bad5e7f1e@d3adb33f:vigi2$ 
```

**Comment by Zorgatone** [comment]
I also tried to install `gulp-sass@2.1.0-beta`, and it worked correctly.

**Comment by xzyfer** [comment]
You were installing the ancient gulp-sass@1. You need to install gulp-sass@2
to get node-sass@3 with node 4 support.

**Comment by Zorgatone** [comment]
That is what was included as depencency by default for the Ionic projects

**Comment by xzyfer** [comment]
We know :( we're trying to get this fixed upstream https://github.com/driftyco/ionic/pull/4449
