### ISSUE TITLE
[Windows 10] error 404: I cannot install into local project, but I can install as global

### ISSUE THREAD

**Issue by Xarkam** [dlmanning/gulp-sass#373]
I cannot install gulp-sass to my project :
```bash
E:\Developpements\jcm-nextgen>npm install gulp-sass --python=c:\python27\python.exe
npm WARN package.json jcm-next@1.0.0 No repository field.
npm WARN package.json jcm-next@1.0.0 No license field.
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
\
> node-sass@2.1.1 install E:\Developpements\jcm-nextgen\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/win32-x64-node-4.2/binding.node

> node-sass@2.1.1 postinstall E:\Developpements\jcm-nextgen\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 32-bit node.lib
gyp ERR! stack     at Request.<anonymous> (E:\Developpements\jcm-nextgen\node_modules\gulp-sass\node_modules\node-sass\node_modules\pangyp\lib\install.js:377:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (E:\Developpements\jcm-nextgen\node_modules\gulp-sass\node_modules\node-sass\node_modules\pangyp\node_modules\request\request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Developpements\\jcm-nextgen\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\pangyp\\bin\\node-gyp" "rebuild"
gyp ERR! cwd E:\Developpements\jcm-nextgen\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v4.2.1
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
Build failed
gulp-sass@1.3.3 node_modules\gulp-sass
├── clone@0.1.19
├── map-stream@0.1.0
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
└── node-sass@2.1.1 (get-stdin@4.0.1, object-assign@2.1.1, replace-ext@0.0.1, semver@4.3.6, cross-spawn@0.2.9, shelljs@0.3.0, chalk@0.5.1, mkdirp@0.5.1, gaze@0.5.2, nan@1.9.0, sass-graph@1.3.0, meow@3.4.2, npmconf@2.1.2, mocha@2.3.
3, request@2.65.0, pangyp@2.3.2)

```
but global install work :
```bash
E:\Developpements\jcm-nextgen>npm install -g gulp-sass --python=c:\python27\python.exe

> spawn-sync@1.0.13 postinstall C:\Users\Benjamin\AppData\Roaming\npm\node_modules\gulp-sass\node_modules\node-sass\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

/
> node-sass@3.3.3 install C:\Users\Benjamin\AppData\Roaming\npm\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\Users\Benjamin\AppData\Roaming\npm\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64-46\binding.node

> node-sass@3.3.3 postinstall C:\Users\Benjamin\AppData\Roaming\npm\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

` C:\Users\Benjamin\AppData\Roaming\npm\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64-46\binding.node ` exists.
 testing binary.
Binary is fine; exiting.
gulp-sass@2.0.4 C:\Users\Benjamin\AppData\Roaming\npm\node_modules\gulp-sass
├── object-assign@2.1.1
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, fancy-log@1.1.0, lodash._reinterpolate@3.0.0, beeper@1.1.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, vinyl@0.5.3, gulplog@1.0.0, lodash.template@3.6.2, chalk@1.1.1, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── node-sass@3.3.3 (get-stdin@4.0.1, async-foreach@0.1.3, chalk@1.1.1, nan@2.1.0, mkdirp@0.5.1, glob@5.0.15, npmconf@2.1.2, gaze@0.5.2, meow@3.4.2, cross-spawn@2.0.0, request@2.65.0, node-gyp@3.0.3, sass-graph@2.0.1)
```
Why cannot install into my project ?

Thanks.

**Comment by xzyfer** [comment]
Your global install is installing node-sass@3.3.3. The other is installing
node-sass@2.1.1. This version is very old and does not support Node 4.
