### ISSUE TITLE
ambiguious error

### ISSUE THREAD

**Issue by sunilw** [dlmanning/gulp-sass#381]
I've pretty much copied an example from the readme. My adaptation looks like this:

`gulp.task('styles', function() {
    gulp.src('./src/src/sass/**')
	.pipe(sass().on('error'), sass.logError)    
	.pipe(gulp.dest('./css/main.css')) ;    
}) ;
`
When I run 'gulp styles', I get this output:

`/home/mantis/.npm-packages/lib/node_modules/gulp/node_modules/orchestrator/index.js:47
			throw new Error('Task '+name+' can\'t support dependencies that is not an a
			      ^
Error: Task default can't support dependencies that is not an array of strings
    at Gulp.Orchestrator.add (/home/mantis/.npm-packages/lib/node_modules/gulp/node_modules/orchestrator/index.js:47:10)
    at Object.<anonymous> (/home/mantis/web/videotest/gulpfile.js:15:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/home/mantis/.npm-packages/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/mantis/.npm-packages/lib/node_modules/gulp/node_modules/liftoff/index.js:181:16)`

The critical line seems to be this one:
`throw new Error('Task '+name+' can\'t support dependencies that is not an a`

This could be more useful. There isn't any indication of which task has an issue, or what exactly is missing.

**Comment by xzyfer** [comment]
This is a gulp error message. As the message says your default task should
be an array.

```
gulp.task('default', ['sass'])
```

**Comment by xzyfer** [comment]
Or it could be that gulp.src needs to an array. Either way this is a gulp
issue.
