### ISSUE TITLE
Error installing, node-sass dependency

### ISSUE THREAD

**Issue by jme783** [dlmanning/gulp-sass#392]
I can no longer install `gulp-sass`, and getting this error when running `npm install`:

```
> spawn-sync@1.0.14 postinstall /Users/Jeff/Documents/particle-apps/device-setup/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

\
> node-sass@3.4.2 install /Users/Jeff/Documents/particle-apps/device-setup/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

/Users/Jeff/Documents/particle-apps/device-setup/node_modules/gulp-sass/node_modules/node-sass/node_modules/npmconf/node_modules/nopt/lib/nopt.js:210
    if (t && ((type.name && t.type.name) ?
                   ^

TypeError: Cannot read property 'name' of null
    at validate (/Users/Jeff/Documents/particle-apps/device-setup/node_modules/gulp-sass/node_modules/node-sass/node_modules/npmconf/node_modules/nopt/lib/nopt.js:210:20)
    at validate (/Users/Jeff/Documents/particle-apps/device-setup/node_modules/gulp-sass/node_modules/node-sass/node_modules/npmconf/node_modules/nopt/lib/nopt.js:179:11)
    at /Users/Jeff/Documents/particle-apps/device-setup/node_modules/gulp-sass/node_modules/node-sass/node_modules/npmconf/node_modules/nopt/lib/nopt.js:101:12
    at Array.map (native)
    at /Users/Jeff/Documents/particle-apps/device-setup/node_modules/gulp-sass/node_modules/node-sass/node_modules/npmconf/node_modules/nopt/lib/nopt.js:67:15
    at Array.forEach (native)
    at Function.clean (/Users/Jeff/Documents/particle-apps/device-setup/node_modules/gulp-sass/node_modules/node-sass/node_modules/npmconf/node_modules/nopt/lib/nopt.js:55:21)
    at /Users/Jeff/Documents/particle-apps/device-setup/node_modules/gulp-sass/node_modules/node-sass/node_modules/npmconf/npmconf.js:411:10
    at Array.forEach (native)
    at validate (/Users/Jeff/Documents/particle-apps/device-setup/node_modules/gulp-sass/node_modules/node-sass/node_modules/npmconf/npmconf.js:410:11)
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jeff/Documents/particle-apps/device-setup/npm-debug.log
```

Any ideas?

**Comment by woodne** [comment]
:+1: I am also getting this

**Comment by Keats** [comment]
As reported in the error message this is a node-sass error, have you reported it there?

**Comment by jme783** [comment]
Weird...now I'm not getting this error anymore...maybe a temp issue with `node-sass`?
