### ISSUE TITLE
Missing Error Message

### ISSUE THREAD

**Issue by lukepolo** [dlmanning/gulp-sass#409]
/var/www/html/mint/20151202151933/node_modules/gulp-util/lib/PluginError.js:73
  if (!this.message) throw new Error('Missing error message');
                           ^
Error: Missing error message
    at new PluginError (/var/www/html/mint/20151202151933/node_modules/gulp-util/lib/PluginError.js:73:28)
    at DestroyableTransform.logError (/var/www/html/mint/20151202151933/node_modules/gulp-sass/index.js:168:17)
    at DestroyableTransform.emit (events.js:117:20)
    at afterTransform (/var/www/html/mint/20151202151933/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:75:19)
    at TransformState.afterTransform (/var/www/html/mint/20151202151933/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:59:12)
    at errorM (/var/www/html/mint/20151202151933/node_modules/gulp-sass/index.js:123:14)
    at DestroyableTransform._transform (/var/www/html/mint/20151202151933/node_modules/gulp-sass/index.js:151:16)
    at DestroyableTransform.Transform._read (/var/www/html/mint/20151202151933/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/var/www/html/mint/20151202151933/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/var/www/html/mint/20151202151933/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:333:12)
[git@mintdev1 current]$

**Comment by lukepolo** [comment]
Any ideas?

**Comment by Keats** [comment]
Not really no, what does the gulp task looks like?

**Comment by lukepolo** [comment]
gulp.src([
            paths.sass + 'app.scss',
            paths.sass + 'admin.scss',
            paths.sass + 'theme_1.scss'
        ])
            .pipe(
            sass.sync({
                outputStyle: 'compressed',
                includePaths: [
                    paths.bootstrap+'stylesheets',
                    paths.fontawesome+'scss'
                ],
                errLogToConsole: true
            }).on(
                'error', sass.logError
            )
        )
            .pipe(sourcemaps.init())
            .pipe(
            autoprefixer({
                browsers: [
                    'last 2 version'
                ]
            })
        )
            .pipe(sourcemaps.write('.'))
            .pipe(gulp.dest(paths.css_public));

**Comment by lukepolo** [comment]
I did a little more debugging and found that if i remove the autoprefixer it works

**Comment by lukepolo** [comment]
it was my node version was compatible

**Comment by MisterDev** [comment]
It happened to me when I was using undeclared variables: `background-color: $main-color`
