### ISSUE TITLE
Installation of gulp-sass fails at build.js

### ISSUE THREAD

**Issue by alliwalk** [dlmanning/gulp-sass#416]
Going through a gulp tutorial on Treehouse where the next set of tasks requires gulp-sass to be installed. I cannot install gulp-sass. Since gulp-sass installs node-sass, I don't have node-sass either. 

The error messages say:
````
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
````

Made sure I updated npm and node before trying again. Running npm v3.3.12, node v5.2.0, OS X v10.6.8. (Gulp-Sass is not installed)

Here are all the errors, and the npm-debug.log file (attached as txt).

````
> npm install gulp-sass --save-dev
npm WARN prefer global node-gyp@3.2.1 should be installed with -g

> node-sass@3.4.2 install /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-sass/vendor/darwin-x64-47/binding.node

> spawn-sync@1.0.13 postinstall /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/spawn-sync
> node postinstall


> node-sass@3.4.2 postinstall /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-sass
> node scripts/build.js

` /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-sass/vendor/darwin-x64-47/binding.node ` exists. 
 testing binary.
Problem with the binary.
Manual build incoming.
Building: /usr/local/Cellar/node/5.2.0/bin/node /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/Cellar/node/5.2.0/bin/node',
gyp verb cli   '/Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.2.1
gyp info using node@5.2.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.11\n"
gyp verb get node dir no --target version specified, falling back to host node version: 5.2.0
gyp verb command install [ '5.2.0' ]
gyp verb install input version string "5.2.0"
gyp verb install installing version: 5.2.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 5.2.0
gyp verb build dir attempting to create "build" dir: /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/alliwalk/.node-gyp/5.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/alliwalk/.node-gyp/5.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/alliwalk/.node-gyp/5.2.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.3.2"' -I/Users/alliwalk/.node-gyp/5.2.0/include/node -I/Users/alliwalk/.node-gyp/5.2.0/src -I/Users/alliwalk/.node-gyp/5.2.0/deps/uv/include -I/Users/alliwalk/.node-gyp/5.2.0/deps/v8/include -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-stdlib=libc++"
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System Darwin 10.8.0
gyp ERR! command "/usr/local/Cellar/node/5.2.0/bin/node" "/Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/node_modules/node-sass
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
Build failed
treehouse-gulp-basics@1.0.0 /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics
├─┬ gulp@3.9.0
│ └─┬ gulp-util@3.0.7
│   └── through2@2.0.0 
├─┬ gulp-sourcemaps@1.6.0
│ └── through2@2.0.0 
└─┬ gulp-uglify@1.5.1
  └── through2@2.0.0 

npm ERR! Darwin 10.8.0
npm ERR! argv "/usr/local/Cellar/node/5.2.0/bin/node" "/usr/local/bin/npm" "install" "gulp-sass" "--save-dev"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alliwalk/Documents/Education/Online/Treehouse/Gulp Basics/treehouse-gulp-basics/npm-debug.log

````

[npm-debug.log.txt](https://github.com/dlmanning/gulp-sass/files/64669/npm-debug.log.txt)

**Comment by xzyfer** [comment]
Two problems. First your osx version is too old for our precompiled binaries. Secondly you're unable to build your own binary because you do not have python installed.

```
brew install python2
```
