### ISSUE TITLE
no suitable image found

### ISSUE THREAD

**Issue by wzl610** [dlmanning/gulp-sass#454]
When I add gulp-sass into my project and write gulpfile.js as "Basic Usage" write,but when I start gulp`s task,it shows me as bottom:

``` code
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/Users/AllenWang/Documents/project/h5model/node_modules/node-sass/vendor/darwin-x64-46/binding.node, 1): no suitable image found.  Did find:
    /Users/AllenWang/Documents/project/h5model/node_modules/node-sass/vendor/darwin-x64-46/binding.node: truncated mach-o error: segment __TEXT extends to 1167360 which is past end of file 678448
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/AllenWang/Documents/project/h5model/node_modules/node-sass/lib/index.js:16:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

I have reinstall gulp-sass and update my nodejs and npm version,but it also show this error.Can you help me?

**Comment by liuyanzhi08** [comment]
+1    node(v 6.2.2) npm (v 3.9.5)

**Comment by Flobin** [comment]
I am encountering the same issue. Did you ever figure out how to solve this?

**Comment by clwm01** [comment]
@Flobin Great, you really resolved my problem!

**Comment by wencongsheng** [comment]
thanks

**Comment by wencongsheng** [comment]
@Flobin thanks！！

**Comment by Gandalf-Pl** [comment]
@Flobin thanks! solved my problem.

**Comment by Ashish7249** [comment]
@Flobin thanks.Everybody encountering this problem must first do  npm install node-sass,if problem resolved then OK,else npm rebuild node-sass

**Comment by ToBeEngineer** [comment]
@Flobin Thanks! It solved My problem.

**Comment by sy0uta1k0n** [comment]
@Flobin Fix my issue, tks a lot!!!!

**Comment by kaybie3** [comment]
@Flobin - thanks for that - helped me out
