### ISSUE TITLE
gulp-sass module can't be installed

### ISSUE THREAD

**Issue by ihefeng** [dlmanning/gulp-sass#455]
### --------- Error info ----------
at Error (native)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.<anonymous> (E:\source\iboxpay\do
de_modules\node-sass\lib\index.js:16:15)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)

**Comment by xzyfer** [comment]
Update to v2.3.1.
