### ISSUE TITLE
2.3.2 Broke My Build

### ISSUE THREAD

**Issue by bilbosan** [dlmanning/gulp-sass#511]
(Possibly in compbination with bulk-sass).

I've narrowed it down and the key variable is the upgrade from gulp-sass 2.3.1 to 2.3.2. on 2.3.1, the following works fine:

``` javascript
gulp.task('styles', ['clean_styles', 'assets'], function() {
  return gulp.src('src/styles/application.scss')
    .pipe(bulkSass())
    .pipe(sass('src/styles/application.scss', { outputStyle: 'expanded', includePaths: ['src/styles'] }))
    .pipe(autoprefixer('last 2 version'))
    .pipe(gulp.dest(destination_paths.css))
});
```

After 2.3.2, I get the error:

```
TypeError: Cannot assign to read only property 'data' of src/styles/application.scss
    at DestroyableTransform._transform (/Users/patrickminton/src/exm-admin-tool/node_modules/gulp-sass/index.js:38:15)
    at DestroyableTransform.Transform._read (/Users/patrickminton/src/exm-admin-tool/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/patrickminton/src/exm-admin-tool/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/patrickminton/src/exm-admin-tool/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/patrickminton/src/exm-admin-tool/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/patrickminton/src/exm-admin-tool/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/Users/patrickminton/src/exm-admin-tool/node_modules/gulp-sass-bulk-import/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/patrickminton/src/exm-admin-tool/node_modules/gulp-sass-bulk-import/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/patrickminton/src/exm-admin-tool/node_modules/gulp-sass-bulk-import/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7)
    at emitReadable_ (/Users/patrickminton/src/exm-admin-tool/node_modules/gulp-sass-bulk-import/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/patrickminton/src/exm-admin-tool/node_modules/gulp-sass-bulk-import/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/patrickminton/src/exm-admin-tool/node_modules/gulp-sass-bulk-import/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/patrickminton/src/exm-admin-tool/node_modules/gulp-sass-bulk-import/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/patrickminton/src/exm-admin-tool/node_modules/gulp-sass-bulk-import/node_modules/readable-stream/lib/_stream_transform.js:145:32)
```

**Comment by xzyfer** [comment]
Please remove everything that isn't gulp-sass to confirm it's not another plugin doing something wrong.

**Comment by bilbosan** [comment]
I cannot confirm that. It may well be an interaction between gulp-sass and one of the other plugins. I wouldn't be able to just "remove everything" else, because I'd have to re-write my stylesheets to work without `gulp-sass-bulk-import`.

I CAN confirm that if I do this in my package.json it works:

`"gulp-sass" : "2.3.1"`

And that if I change NOTHING ELSE, but bump that to this, it breaks:

`"gulp-sass" : "2.3.2"`

**Comment by xzyfer** [comment]
> And that if I change NOTHING ELSE, but bump that to this, it breaks

I understand this. However the change in gulp-sass was harmless. It would have only caused an issue if another plugin was doing something it shouldn't be.

Looking at the issue a little deeper it looks like it originates in `gulp-sass-bulk-import` but the cause is not clear. Somewhere the options object being passed into gulp-sass is being marked an non-extensible.

**Comment by yusk90** [comment]
Same here, stopped working after update to 2.3.2, with 2.3.1 works.
```javascript
gulp.task('style', function () {
    return gulp.src('scss/style.scss')
    .pipe(sass('style.css'))
    .pipe(gulp.dest(params.out))
    .pipe(reload({ stream: true }));
});
```
```
TypeError: Cannot assign to read only property 'data' of style.css
at DestroyableTransform._transform (/home/prog5/test/node_modules/gulp-sass/index.js:38:15)
at DestroyableTransform.Transform._read (/home/prog5/test/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
at DestroyableTransform.Transform._write (/home/prog5/test/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
at doWrite (/home/prog5/test/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
at writeOrBuffer (/home/prog5/test/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
at DestroyableTransform.Writable.write (/home/prog5/test/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
at DestroyableTransform.ondata (/home/prog5/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
at emitOne (events.js:77:13)
at DestroyableTransform.emit (events.js:169:7)
at readableAddChunk (/home/prog5/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:198:18)
at DestroyableTransform.Readable.push (/home/prog5/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:157:10)
at DestroyableTransform.Transform.push (/home/prog5/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:123:32)
at afterTransform (/home/prog5/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:51)
at TransformState.afterTransform (/home/prog5/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
at /home/prog5/test/node_modules/gulp/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:18:5
at /home/prog5/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:78:16
```

**Comment by xzyfer** [comment]
@yusk90 that is not a valid way to use this plugin. The only thing you can pass into `sass()` is a configuration object.

**Comment by yusk90** [comment]
@xzyfer Yes, you're right, don't remember where it came from though :)
