### ISSUE TITLE
TypeError: Cannot assign to read only property 'data' of ./

### ISSUE THREAD

**Issue by cristidraghici** [dlmanning/gulp-sass#513]
I am rather new to using gulp and I have encountered the error above using it on my Windows 10 machine. Details:

```
Saving To...
   - public/css/app.css

C:\_dev\my-app\node_modules\gulp-sass\index.js:38
    opts.data = file.contents.toString();
              ^

TypeError: Cannot assign to read only property 'data' of ./
    at DestroyableTransform._transform (C:\_dev\my-app\node_modules\gulp-sass\index.js:41:15)
    at DestroyableTransform.Transform._read (C:\_dev\my-app\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (C:\_dev\my-app\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\_dev\my-app\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (C:\_dev\my-app\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (C:\_dev\my-app\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at DestroyableTransform.ondata (C:\_dev\my-app\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:531:20)
    at emitOne (events.js:90:13)
    at DestroyableTransform.emit (events.js:182:7)
    at readableAddChunk (C:\_dev\my-app\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:198:18)
```

I have added, above the line with the error some console logs:
```
    opts = clonedeep(options || {});
	console.log(options);
	console.log(opts);
	console.log(typeof opts);
    opts.data = file.contents.toString();
```
and got the following:
```
Saving To...
   - public/css/app.css

./
./
string
C:\_dev\my-app\node_modules\gulp-sass\index.js:41
    opts.data = file.contents.toString();
              ^

TypeError: Cannot assign to read only property 'data' of ./
```

I am using gulp with laravel-elixir and inside the file, the code generating the error is:
```
    mix.sass([
        'app.scss',
    ], 'public/css/app.css', './');
```

I was able to get results by replacing line #37 in the gulp-sass/index.js file:
`opts = clonedeep(options || {});`
with
`opts = {};`

But this is just a bad patch to get things going. Therefore, I would appreciate any support you can give me.

Kind regards and thanks!

**Comment by xzyfer** [comment]
What is `mix.sass`? Gulp Sass takes a settings object as its only argument.
The src files must come `gulp.src`. The error you're seeing is because
options is a string not an object.

**Comment by xzyfer** [comment]
Please check to readme to make sure you're using gulp-sass correctly.

**Comment by cristidraghici** [comment]
mix.sass comes from laravel-elixir:
```
var elixir = require('laravel-elixir'),
    gulp = require('gulp');

elixir(function (mix) {
...
}
```
Thank you for your comments. I will look into that.
