### ISSUE TITLE
Failed to map segment from shared object

### ISSUE THREAD

**Issue by fradnetcom** [dlmanning/gulp-sass#521]
**Error code:**

```
$ gulp
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /xxx/xxxx/xxx/node_modules/node-sass/vendor/linux-x64-46/binding.node: failed to map segment from shared object
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/xxx/xxxx/xxx/node_modules/node-sass/lib/index.js:24:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
```

System info:

```
npm -v 
3.5.2
```

```
node -v
v4.2.6
```

```
node -p process.versions
{ http_parser: '2.5.0',
  node: '4.2.6',
  v8: '4.5.103.35',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '55.1',
  modules: '46',
  openssl: '1.0.2g-fips' }
```

```
node -p process.platform
linux
```

```
node -p process.arch
x64
```

`"gulp-sass": "^2.3.2",`

**Comment by michmzr** [comment]
Upvoted. I have the same problem on Ubuntu 14.04.5 LTS

**Comment by fradnetcom** [comment]
I have too Ubuntu but other version: Ubuntu Mate 16.04

**Comment by fradnetcom** [comment]
This not help

**Comment by K4LiN** [comment]
I've encountered a similar problem. Maybe it's related: https://github.com/sass/node-sass/issues/1407
Good luck.

**Comment by michmzr** [comment]
I resolved my problem by change in configuration of /etc/fstab.  I have a few mounted partitions on the server. One was for /usr, other is for /var/www, where I have my web projects. I had to give flash data=exec, and then reboot system, reinstall node_modules in project directory.

`UUID="b0d7a164-2536-4c2a-98f7-cdc6c3107c45"	/var/www 	ext4    rw,relatime,data=ordered,exec		0       2 
`
