### ISSUE TITLE
Gulp-sass node modules error - failed to build project via jenkins

### ISSUE THREAD

**Issue by frieman** [dlmanning/gulp-sass#529]
Since today morning i failed to build my project via Jenkins job and deploy it to amazon, 
I think the issue is because, today there was a new node-sass  release v0.3.9  - that i think broke gulp-sass node-module (see below)

AWSEB Deployment Plugin Version 0.3.10
Zipping contents of Root File Object (community commit builds) into tmp file awseb-4760291425392070535.zip (includes=, excludes=)
FATAL: Deployment Failure
java.io.IOException: Deployment Failure
	at br.com.ingenieux.jenkins.plugins.awsebdeployment.AWSEBDeploymentBuilder.perform(AWSEBDeploymentBuilder.java:171)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: java.util.concurrent.ExecutionException: hudson.os.PosixException: native error calling stat: No such file or directory /home/jenkins/workspace/community commit builds/node_modules/gulp-sass/node_modules/node-sass/test/fixtures/spec/spec/libsass/Sa??ss-UT??F8 ENOENT
	at hudson.remoting.Channel$2.adapt(Channel.java:829)
	at hudson.remoting.Channel$2.adapt(Channel.java:824)
	at hudson.remoting.FutureAdapter.get(FutureAdapter.java:55)
	at br.com.ingenieux.jenkins.plugins.awsebdeployment.DeployerRunner.perform(DeployerRunner.java:66)
	at br.com.ingenieux.jenkins.plugins.awsebdeployment.AWSEBDeploymentBuilder.perform(AWSEBDeploymentBuilder.java:167)

**Comment by xzyfer** [comment]
Sorry I don't understand what I'm looking at, I don't do Java. It looks you're having an issue with utf-8 file names

>No such file or directory /home/jenkins/workspace/community commit builds/node_modules/gulp-sass/node_modules/node-sass/test/fixtures/spec/spec/libsass/Sa??ss-UT??F8 ENOENT

**Comment by jobo26** [comment]
Same problem for me on Jenkins. A new version of node-sass has been released [today](https://github.com/sass/node-sass/releases). I think that might be the cause of this problem.

**Comment by xzyfer** [comment]
Yes I released that version. However without understand the problem it can't be fixed.

**Comment by frieman** [comment]
This is Java because of Jenkins job trying to zip the project before deploying it to AWS.
What i saw is that the output of the npm install is a file with known UTF-8 name in the dist directory: 
node_modules/gulp-sass/node_modules/node-sass/test/fixtures/spec/spec/libsass/

**Comment by Alain-Bearez** [comment]
The fact is that `node-sass` began including its `test` directory since version *3.9.0*, where some directory name in `sass-spec` has a name with UTF-8 characters for putting an acute over preceding letter and a cedilla under other letter.

I would recommend to update the dependencies so that `gulp-sass` would limit itself to `node-sass` being **at most** `3.7.0`, where the `test` directory is not exported. At least until `node-sass` maintainers consider their practice to be armful to part of the community, using Jenkins or Bamboo.

**Comment by xzyfer** [comment]
> would recommend to update the dependencies so that gulp-sass would limit itself to node-sass being at most 3.8.0

We will not do this. It would defeat the purpose of gulp-sass. Feel free to shrink wrap your dependencies if you wish.

> At least until node-sass maintainers consider their practice to be armful to part of the community

We do not consider this harmful.

> Hudson, Jenkins or Bamboo which are based on Java where some rules are enforced on file names

This is not the case. As pointed out in https://github.com/sass/node-sass/issues/1699#issuecomment-244801171 this is a known bug in Jenkins. There are existing work arounds in.

https://issues.jenkins-ci.org/browse/JENKINS-12610
https://issues.jenkins-ci.org/browse/JENKINS-33478
