### ISSUE TITLE
Cannot find module 'gulp-sass

### ISSUE THREAD

**Issue by kevincaradant** [dlmanning/gulp-sass#544]
Hi :),

I get this error and the only to fixed it, it's to install it manually but, I have the lib in the package.json so it's weird 

```
[15:31:57] Error: Cannot find module 'gulp-sass' from 'C:\Users\Documents\projets\jira-cards-web'
    at Function.module.exports [as sync] (C:\Users\Documents\projets\jira-cards-web\node_modules\resolve\lib\sync.js:33:11)
    at requireFn (C:\Users\Documents\projets\jira-cards-web\node_modules\gulp-load-plugins\index.js:46:25)
    at Object.defineProperty.get (C:\Users\m418631\Documents\projets\jira-cards-web\node_modules\gulp-load-plugins\index.js:84:18)
[15:31:57] The following tasks did not complete: scripts
[15:31:57] Did you forget to signal async completion?
```

Did you have any idea why I get this error ? 
Is it link with node-sass problem maybe ? 

Thanks

OS: Windows 7
Node: 6.4
GULP-SASS: 2.3.2

**Comment by xzyfer** [comment]
Looks like you have misconfigured `gulp-load-plugins`. Please double check their documentation and open an issue with them.

**Comment by kevincaradant** [comment]
OK it's just `gulp-sass` is not installed in node_modules that's why gulp-load-plugins said me `Cannot find module 'gulp-sass'`. Before that works so I don't know what changed.
