### ISSUE TITLE
error for installing with yarn package manage

### ISSUE THREAD

**Issue by alireza-saberi** [dlmanning/gulp-sass#593]
With npm, it is ok but with Yarn it throw the following error.
```
yarn install v0.19.1
warning secret-santa@1.0.0: License should be a valid SPDX license expression
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
██████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░ 8845/10311e
vents.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TLSWrap.onread (net.js:544:26)
```

**Comment by xzyfer** [comment]
```
Error: read ECONNRESET
```
The network connection was reset. Try `yarn` again.
