### ISSUE TITLE
`npm install` fails due to missing bindings on Node 6.x on Linux 64-bit

### ISSUE THREAD

**Issue by tinacious** [dlmanning/gulp-sass#594]
`npm install` fails due to missing bindings on Node 6.x. Node Sass now supports Node 6, so should Gulp Sass.

```
/home/ubuntu/my-app/node_modules/gulp-sass/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /home/ubuntu/my-app/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-48/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at module.exports (/home/ubuntu/my-app/node_modules/gulp-sass/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/ubuntu/my-app/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/my-app/node_modules/gulp-sass/index.js:187:21)

```

**Comment by xzyfer** [comment]
You've change from node 4 to 6 with reinstaling your modules.

On 10 Mar. 2017 9:53 am, "Tina Holly" <notifications@github.com> wrote:

npm install fails due to missing bindings on Node 6.x. Node Sass now
supports Node 6, so should Gulp Sass.

/home/ubuntu/my-app/node_modules/gulp-sass/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding
/home/ubuntu/my-app/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-48/binding.node
Node Sass could not find a binding for your current environment: Linux
64-bit with Node.js 6.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 4.x

This usually happens because your environment has changed since
running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at module.exports
(/home/ubuntu/my-app/node_modules/gulp-sass/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous>
(/home/ubuntu/my-app/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>
(/home/ubuntu/my-app/node_modules/gulp-sass/index.js:187:21)


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dlmanning/gulp-sass/issues/594>, or mute the thread
