### ISSUE TITLE
Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)

### ISSUE THREAD

**Issue by SamThilmany** [dlmanning/gulp-sass#628]
I am using `gulp-sass@3.1.0` (currently the lastest version).

When running my gulp task I get this:

```
/Users/samthilmany/<Project>/node_modules/gulp-sass/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.2
    at module.exports (/Users/samthilmany/<Project>/node_modules/gulp-sass/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/samthilmany/<Project>/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/samthilmany/<Project>/node_modules/gulp-sass/index.js:187:21)
```

I'm using macOS 10.13 and am running `node@8.4.0`.

**Comment by xzyfer** [comment]
You need node-sass@4.5.3. delete your node_modules to get the latest
node-sass.

**Comment by BasmaRadadi** [comment]
@xzyfer  Hi , i have the same issue but with windows 10 how can i solve the problem using cmd commands 
thnks for help

**Comment by xzyfer** [comment]
Delete node_modules and npm install

**Comment by TheTonnio** [comment]
Updated node-sass package to 4.7.2 version and it works for me.
