### ISSUE TITLE
Cannot read property 'messageFormatted' of undefined

### ISSUE THREAD

**Issue by gultyaev** [dlmanning/gulp-sass#660]
The error looks so
```
TypeError: Cannot read property 'messageFormatted' of undefined
    at Function.logError (/Users/sergeygultyayev/Projects/mountain/node_modules/gulp-sass/index.js:179:53)
    at Gulp.<anonymous> (/Users/sergeygultyayev/Projects/mountain/gulpfile.js:22:35)
    at module.exports (/Users/sergeygultyayev/Projects/mountain/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/sergeygultyayev/Projects/mountain/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/sergeygultyayev/Projects/mountain/node_modules/orchestrator/index.js:214:10)
    at /Users/sergeygultyayev/Projects/mountain/node_modules/orchestrator/index.js:279:18
    at finish (/Users/sergeygultyayev/Projects/mountain/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/sergeygultyayev/Projects/mountain/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/Users/sergeygultyayev/Projects/mountain/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/sergeygultyayev/Projects/mountain/node_modules/orchestrator/index.js:214:10)
```
And my task looks so
```
gulp.task('css', function() {
  gulp.src('src/scss/index.scss')
    .pipe(sass().on('error', sass.logError()))
    .pipe(gulp.dest('docs'))
    .pipe(connect.reload())
});
```
I can't understand the problem.

**Comment by Blinnikov** [comment]
@gultyaev Try pass function to `.on('error', ...` subscription, not to execute it:
``` javascript
.pipe(sass().on('error', sass.logError))
```
