### ISSUE TITLE
Please help error install

### ISSUE THREAD

**Issue by teremok1000** [dlmanning/gulp-sass#674]
yosemite

`Alexs-iMac:testgulp alex$ sudo npm install
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

> node-sass@4.8.3 install /Users/alex/Desktop/testgulp/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/alex/Desktop/testgulp/node_modules/node-sass/vendor/darwin-x64-59 : { Error: EACCES: permission denied, mkdir '/Users/alex/Desktop/testgulp/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:909:18)
    at sync (/Users/alex/Desktop/testgulp/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/alex/Desktop/testgulp/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/alex/Desktop/testgulp/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/Users/alex/Desktop/testgulp/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/alex/Desktop/testgulp/node_modules/node-sass/vendor' }

> node-sass@4.8.3 postinstall /Users/alex/Desktop/testgulp/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/alex/Desktop/testgulp/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/alex/Desktop/testgulp/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.9.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/alex/Desktop/testgulp/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/alex/Desktop/testgulp/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/alex/Desktop/testgulp/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/alex/Desktop/testgulp/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/alex/Desktop/testgulp/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/alex/Desktop/testgulp/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:170:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/alex/Desktop/testgulp/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/alex/Desktop/testgulp/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/alex/Desktop/testgulp/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/alex/Desktop/testgulp/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/alex/Desktop/testgulp/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/alex/Desktop/testgulp/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:170:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/alex/Desktop/testgulp/node_modules/which/which.js:13:12)\n    at F (/Users/alex/Desktop/testgulp/node_modules/which/which.js:68:19)\n    at E (/Users/alex/Desktop/testgulp/node_modules/which/which.js:80:29)\n    at /Users/alex/Desktop/testgulp/node_modules/which/which.js:89:16\n    at /Users/alex/Desktop/testgulp/node_modules/isexe/index.js:42:5\n    at /Users/alex/Desktop/testgulp/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:170:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.9.0
gyp verb command install [ '9.9.0' ]
gyp verb install input version string "9.9.0"
gyp verb install installing version: 9.9.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.9.0
gyp verb build dir attempting to create "build" dir: /Users/alex/Desktop/testgulp/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/alex/Desktop/testgulp/node_modules/node-sass/build'
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/alex/Desktop/testgulp/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/alex/Desktop/testgulp/node_modules/node-sass
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN Coderiver-Project@0.2.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.8.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.8.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex/.npm/_logs/2018-03-26T08_01_44_152Z-debug.log`

**Comment by xzyfer** [comment]
Npm doesn't have permission to write to your desktop. Make sure you're not
running npm as sudo or root. If you are you need to use the --unsafe-perms
flag. Otherwise make sure you have write access to the folder where you
code is.

**Comment by teremok1000** [comment]
not working, another hdd

`Alexs-iMac:testgulp alex$ sudo npm install --unsafe-perms

> node-sass@4.8.3 install /Volumes/Files more/testgulp/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Volumes/Files more/testgulp/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission denied, mkdir '/Volumes/Files more/testgulp/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/Volumes/Files more/testgulp/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Volumes/Files more/testgulp/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Volumes/Files more/testgulp/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/Volumes/Files more/testgulp/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Volumes/Files more/testgulp/node_modules/node-sass/vendor' }

> node-sass@4.8.3 postinstall /Volumes/Files more/testgulp/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Volumes/Files more/testgulp/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Volumes/Files more/testgulp/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Volumes/Files more/testgulp/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Volumes/Files more/testgulp/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Volumes/Files more/testgulp/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Volumes/Files more/testgulp/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Volumes/Files more/testgulp/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Volumes/Files more/testgulp/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Volumes/Files more/testgulp/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Volumes/Files more/testgulp/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Volumes/Files more/testgulp/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Volumes/Files more/testgulp/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Volumes/Files more/testgulp/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Volumes/Files more/testgulp/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Volumes/Files more/testgulp/node_modules/which/which.js:13:12)\n    at F (/Volumes/Files more/testgulp/node_modules/which/which.js:68:19)\n    at E (/Volumes/Files more/testgulp/node_modules/which/which.js:80:29)\n    at /Volumes/Files more/testgulp/node_modules/which/which.js:89:16\n    at /Volumes/Files more/testgulp/node_modules/isexe/index.js:42:5\n    at /Volumes/Files more/testgulp/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.10.0
gyp verb command install [ '8.10.0' ]
gyp verb install input version string "8.10.0"
gyp verb install installing version: 8.10.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.10.0
gyp verb build dir attempting to create "build" dir: /Volumes/Files more/testgulp/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Volumes/Files more/testgulp/node_modules/node-sass/build'
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/Volumes/Files more/testgulp/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Volumes/Files more/testgulp/node_modules/node-sass
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN Coderiver-Project@0.2.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.8.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.8.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex/.npm/_logs/2018-03-26T08_13_37_017Z-debug.log
Alexs-iMac:testgulp alex$ 
`
