### ISSUE TITLE
Gulp Unexpected Token SCSS

### ISSUE THREAD

**Issue by sswamidass** [dlmanning/gulp-sass#697]
Gulp File

'use strict';

//dependancies
var gulp = require('gulp');
var sass = require('gulp-sass');
var minifyCSS = require('gulp-clean-css');
var uglify = require('gulp-uglify');
var rename = require('gulp-rename');
var changed = require('gulp-changed');

// - SCSS/CSS

var SCSS_SRC = './src/Assets/scss/**/*.scss';
var SCSS_DEST = './src/Assets/css';

gulp.task('compile_scss', function() {

  gulp.src(SCSS_SRC)
  .pipe(sass().on('error', sass.logError))
  .pipe(minifyCSS())
  .pipe(rename({ suffix: '.min' }))
  .pipe(changed(SCSS_DEST))
  .pipe(gulp.dest(SCSS_DEST));

});

gulp.task('watch_scss', function() {
  .gulp.watch(SCSS_SRC, ['compile_scss']);
});

gulp.task('default', ['watch_scss']);

Output
/Users/ss/Desktop/reactTest/my-app/gulpfile.js:31
  .gulp.watch(SCSS_SRC, ['compile_scss']);
  ^

SyntaxError: Unexpected token .
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
Sanjays-MBP-3:my-app sanjayswamidass$

**Comment by xzyfer** [comment]
```diff
gulp.task('watch_scss', function() {
-.gulp.watch(SCSS_SRC, ['compile_scss']);
+gulp.watch(SCSS_SRC, ['compile_scss']);
});
```

**Comment by sswamidass** [comment]
Any Ideas?


AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/ss/Desktop/reactTest/my-app/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/ss/Desktop/reactTest/my-app/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/ss/Desktop/reactTest/my-app/gulpfile.js:34:6)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by xzyfer** [comment]
No I don't use gulp personally. Try asking on StackOverflow or Google.
