### ISSUE TITLE
Cannot install this on Mac OS X?

### ISSUE THREAD

**Issue by sabsaxo** [dlmanning/gulp-sass#717]
I've been getting this for the past two days:

```
Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Applications/MAMP/htdocs//wp-content/themes/mytheme/gulpfile.js:2:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

```
And having a hell installing node-sass as well ...

And yes, I'm just trying to run: `npm i` with an alredy existing package.json ... so please, don't go there.

**Comment by xzyfer** [comment]
Looks like the issue is environmental not specific to node-sass. Make sure you're not using sudo or use the --unsafe-perms flag when running npm install.

**Comment by simonboak** [comment]
I'm having the same problem here, installing the package is resulting in a 404:

`> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node": 

HTTP error 404 Not Found`

**Comment by WuglyakBolgoink** [comment]
```bash
# clean
rm -rf node_modules package-lock.json
# remove gulp-sass from package.json
# install all what u have
npm i 
#after that
npm i node-sass --unsafe-perms -D
npm rebuild node-sass
npm i gulp-sass -D
```
