### ISSUE TITLE
Unable to install gulp-sass on node -v 12.11.1

### ISSUE THREAD

**Issue by kamil-kielczewski** [dlmanning/gulp-sass#749]
When I run command (guided by [this](https://www.npmjs.com/package/gulp-sass))

`npm install node-sass gulp-sass --save-dev`

then I get
```
...
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/root/.node-gyp/12.11.1/include/node -I/root/.node-gyp/12.11.1/src -I/root/.node-gyp/12.11.1/deps/openssl/config -I/root/.node-gyp/12.11.1/deps/openssl/openssl/include -I/root/.node-gyp/12.11.1/deps/uv/include -I/root/.node-gyp/12.11.1/deps/zlib -I/root/.node-gyp/12.11.1/deps/v8/include -I../../../../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/create_string.o.d.raw   -c -o Release/obj.target/binding/src/create_string.o ../src/create_string.cpp
../src/create_string.cpp: In function 'char* create_string(Nan::MaybeLocal<v8::Value>)':
../src/create_string.cpp:17:37: error: no matching function for call to 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)'
   v8::String::Utf8Value string(value);
                                     ^
In file included from /root/.node-gyp/12.11.1/include/node/node.h:63:0,
                 from ../../../../../nan/nan.h:54,
                 from ../src/create_string.cpp:1:
/root/.node-gyp/12.11.1/include/node/v8.h:3039:5: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~~~~~
/root/.node-gyp/12.11.1/include/node/v8.h:3039:5: note:   candidate expects 2 arguments, 1 provided
binding.target.mk:129: recipe for target 'Release/obj.target/binding/src/create_string.o' failed
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
make: Leaving directory '/work/code/ebi/ebnavi/ebnavi.com/node_modules/@angular-devkit/build-angular/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/work/code/ebi/ebnavi/ebnavi.com/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/bin/node" "/work/code/ebi/ebnavi/ebnavi.com/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /work/code/ebi/ebnavi/ebnavi.com/node_modules/@angular-devkit/build-angular/node_modules/node-sass
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
```

What to do?

**Comment by xzyfer** [comment]
What's the result of npm ls node-sass?

**Comment by kamil-kielczewski** [comment]
Sorry -my bad - this error was caused by library:

`"@angular-devkit/build-angular": "~0.10.0"`

after change its  version to "~0.803.0" error dissapear
