### ISSUE TITLE
require gulp-sass in gulpfile.js fails

### ISSUE THREAD

**Issue by Kontr3X** [dlmanning/gulp-sass#753]
Always when i am trying to require  "gulp-sass" in gulpfile it fails with: 

> 
> D:\Test\File\node_modules\gulp-sass\index.js:15
> const gulpSass = (options, sync) => through.obj((file, enc, cb) => { // eslint
>                                  ^^
> SyntaxError: Unexpected token =>
>     at exports.runInThisContext (vm.js:73:16)
>     at Module._compile (module.js:443:25)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Object.<anonymous> (D:\Test\File\gulpfile.js:4:12)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)
> 
gulp -v
CLI version: 2.2.0
Local version: 4.0.2
node -v
v0.12.2
npm -v
2.7.4

**Comment by Kontr3X** [comment]
Solved - incompatible / wrong version: https://node.green/#ES2015-functions-arrow-functions

- Uninstalled Nodejs,
- deleted the folder,
- installed the latest nodejs,
- Rebuild the project dependencies(...)
